
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLUMN COMMA END FROM SELECT STAR TABLE WHEREstatement : expressionexpression : SELECT columns FROM TABLE ENDrecursive_columns : recursive_columns COMMA COLUMNrecursive_columns : COLUMNcolumns : STAR\n               | recursive_columns'
    
_lr_action_items = {'SELECT':([0,],[2,]),'FROM':([4,5,6,7,11,],[8,-4,-6,-5,-3,]),'COLUMN':([2,9,],[5,11,]),'END':([10,],[12,]),'$end':([1,3,12,],[-1,0,-2,]),'STAR':([2,],[7,]),'TABLE':([8,],[10,]),'COMMA':([5,6,11,],[-4,9,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'recursive_columns':([2,],[6,]),'columns':([2,],[4,]),'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','parsesql.py',41),
  ('expression -> SELECT columns FROM TABLE END','expression',5,'p_expr_select','parsesql.py',46),
  ('recursive_columns -> recursive_columns COMMA COLUMN','recursive_columns',3,'p_recursive_columns','parsesql.py',53),
  ('recursive_columns -> COLUMN','recursive_columns',1,'p_recursive_columns_base','parsesql.py',58),
  ('columns -> STAR','columns',1,'p_columns','parsesql.py',63),
  ('columns -> recursive_columns','columns',1,'p_columns','parsesql.py',64),
]
